Create SpaceHunt.html
halyngoc/CS300-Group3-SpaceHunt pull request #9
Opened 2019-02-08 05:16 UTC by alangomez24

Simon's HTML main page

2019-02-08 05:32 UTC, halyngoc requested changes
- [x] All input elements in a form should be in one single form element. Example from https://www.w3schools.com/html/html_forms.asp

   ```html
   <form>
     <input type="radio" name="gender" value="male" checked> Male<br>
     <input type="radio" name="gender" value="female"> Female<br>
     <input type="radio" name="gender" value="other"> Other
   </form>
   ```

- [x] Use proper indentation, 2 spaces

- [x] Inconsistency with `name=value` vs `name="value"` (for example [here](https://github.com/halyngoc/CS300-Group3-SpaceHunt/pull/9/files#diff-b571208aa78bb8701815736f96a859aeR41)). I'd say go with the 2nd one cause most tutorials I see do that

- [x] `<label for="elementID">`. See [tutorial here](https://www.w3schools.com/tags/tag_label.asp). So for example [here](https://github.com/halyngoc/CS300-Group3-SpaceHunt/pull/9/commits/a79202e7a117efb04b35a51890cb8d2bcb1b6d3e#diff-b571208aa78bb8701815736f96a859aeR11) either do this

   ```html
   <label for="distance">Distance </label>
   <input type=text name=distance id="distance" value=0>
   ```
   or
   ```html
   <label>Distance <input type=text name=distance value=0></label>
   ```

2019-02-08 06:19 UTC, SimonBartonPSU commented
Will work on these fixes and complete movement behavior tomorrow. Good suggestions for sure. 👍

2019-02-10 03:06 UTC, SimonBartonPSU commented
OK I've got my user story to an initial working point. I wanted to get system status info to display with output tags but couldn't figure it out, so the system status displays with input text tags.

2019-02-12 21:30 UTC, SimonBartonPSU approved these changes

2019-02-14 21:58 UTC, halyngoc approved these changes

2019-02-14 23:37 UTC, merged